### ISSUE TITLE
How to run tasks on schedule 

### ISSUE THREAD

**Issue by CodeInFilth** [guanquann/Stocksera#21]
How do you recomend running tasks on a schedule as some of the scripts require you to call them from the root of the project directory.

Your insight here would be helpful as I can only think of hickory and cron jobs and those do not seem to work properly.

**Comment by CodeInFilth** [comment]
Do you have plan on sharing the way you achive this? As I still get errors when running wsb_live() and trying to cron them.

**Comment by spartan737** [comment]
The reason why I didn't share it from the start is because I'm using pythonanywhere to host/run my scheduled tasks, where the method of running a scheduled script is quite different from how we will run on our OS.

<img width="917" alt="img1" src="https://user-images.githubusercontent.com/76832850/147409887-f8267f2e-d75f-461c-8ba5-ad8a0a33192a.PNG">

Basically at the start of every hour (00 mins past), I will run wsb_live() and update_hourly(). Note that you only run update_hourly() once every hour.

For the rest of the hour (in 10mins interval each), I will run wsb_live(), wsb_change() and get_mkt_cap().

tasks_to_run.py is purely for reference. You are free to experiment how you want to run the scripts.
